---
apiVersion: v1
kind: ConfigMap
metadata:
  name: retry-script
data:
  retry.sh: |
    #!/usr/bin/env bash
    ##########################################################################
    # Parse the image url to find information (region, namespace, image name and eventually tag)
    # as url of Image PipelineResource is the complete path to the image, including the registry
    # and the image tag - https://github.com/tektoncd/pipeline/blob/v0.10.1/docs/resources.md#image-resource
    # Environment variables:
    # - IMAGE_RESOURCE_URL (input) : can include a tag
    # - IMAGE_URL (output)
    # - REGISTRY_REGION (output)
    # - REGISTRY_NAMESPACE (output)
    # - IMAGE_NAME (output)
    # - IMAGE_TAG (output)
    ##########################################################################
    echo "woot"
    echo $1
    echo $2
    echo $3
    local n=1
    local max=3
    local delay=2
    while true; do
      "$@" && break || {
        if [[ $n -lt $max ]]; then
          ((n++))
          echo "Command failed. Attempt $n/$max:"
          sleep $delay;
        else
          echo "The command has failed after $n attempts."
  	  exit 1
        fi
      }
    done
